analyzer:
  errors:
    #avoid_print: ignore ignore
    constant_identifier_names: ignore
    deprecated_member_use: ignore
    file_names: ignore
    invalid_use_of_protected_member: ignore
    non_constant_identifier_names: ignore
    prefer_const_constructors: ignore
    prefer_typing_uninitialized_variables: ignore
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false