name: eraphilippines
description: "ERA Philippines"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_staggered_grid_view: ^0.4.0
  get: ^4.6.6
  flutter_screenutil: ^5.9.0
  dio: ^5.4.3+1
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.2.3
  another_carousel_pro: ^1.0.2
  rename: ^3.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  cached_network_image: ^3.3.1
  carousel_slider_plus: ^7.0.0
  curved_navigation_bar: ^1.0.6
  flutter_gemini: ^2.0.4  
  smooth_page_indicator: ^1.2.0+3
  screenshot: ^3.0.0
  image_to_pdf_converter: 0.0.1
  awesome_notifications: any
  permission_handler: ^11.3.1
  awesome_notifications_core: ^0.9.3
  device_info_plus: ^10.1.2
  youtube_player_flutter: ^9.1.1
   
  #firebase
  firebase_core: ^3.2.0
  firebase_storage: ^12.1.1
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  google_sign_in: ^6.2.1
  
  intl: ^0.19.0
  image_picker: ^1.1.2
  dropdown_button2: ^2.3.9
  fl_chart: ^0.68.0
  syncfusion_flutter_charts: ^26.2.4
  dart_eval: ^0.7.9
  number_paginator: ^0.4.1
  easy_sidemenu: ^0.6.0
  webview_flutter: ^4.8.0
  path_provider: ^2.1.4
  http: ^1.2.2
  intl_phone_field: ^3.2.0
  url_launcher: ^6.3.0
  map_location_picker: ^1.3.0
  google_maps_flutter: ^2.9.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  flutter_typeahead: ^4.8.0
  dropdown_search: ^5.0.6
  full_screen_image: ^2.0.0
  circle_nav_bar: ^2.1.0+1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  change_app_package_name: ^1.4.0

flutter_launcher_icons:
  #  image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/images/logowhite.png"
  image_path_ios: "assets/images/logowhite.png" #//1024x1024
  android: "launcher_icon"  
  ios: true
  # min_sdk_android: 21  
  remove_alpha_ios: true
  # background_color_ios: "#ffffff"
  # web:
  #   generate: true
  #   image_path: "assets/images/era_app_icon.png"
  #   background_color: "#hexcode"
  #   theme_color: "#hexcode"
  # windows:
  #   generate: true
  #   image_path: "assets/images/era_app_icon.png"
  #   icon_size: 48 # min:48, max:256, default: 48
  # macos:
  #   generate: true
  #   image_path: "assets/images/era_app_icon.png"



flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/