name: eraphilippines
description: "ERA Philippines"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_staggered_grid_view: ^0.4.0
  get: ^4.6.6
  flutter_screenutil: ^5.9.0
  dio: ^5.4.3+1
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.2.3
  another_carousel_pro: ^1.0.2
  rename: ^3.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_splash_screen: ^3.0.0
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  curved_navigation_bar: ^1.0.6
  flutter_gemini: ^2.0.4  
  smooth_page_indicator: ^1.2.0+3

  #firebase
  firebase_core: ^3.2.0
  firebase_storage: ^12.1.1
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  google_sign_in: ^6.2.1
  intl: ^0.19.0
  image_picker: ^1.1.2
  dropdown_button2: ^2.3.9
  fl_chart: ^0.68.0
  syncfusion_flutter_charts: ^26.2.4
  dart_eval: ^0.7.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/eraph_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/eraph_logo.png"
    background_color: "#hexcode"



flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/