// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrXRGnJ-hpElTnPLxIE704fFM3lwl8hdU',
    appId: '1:257014263809:web:83934a184bee1fd7a5d000',
    messagingSenderId: '257014263809',
    projectId: 'era-philippines',
    authDomain: 'era-philippines.firebaseapp.com',
    databaseURL:
        'https://era-philippines-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'era-philippines.appspot.com',
    measurementId: 'G-2LMF4ESCF6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwxVU4RDoho0zmAeOXXq0uCZU6Z0f4X-0',
    appId: '1:257014263809:android:b49ec21b6dd68c0aa5d000',
    messagingSenderId: '257014263809',
    projectId: 'era-philippines',
    databaseURL:
        'https://era-philippines-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'era-philippines.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsD7EsR8OnW8DyQkDWSP1nuDBPl354NEg',
    appId: '1:257014263809:ios:63fc4aac3df257a9a5d000',
    messagingSenderId: '257014263809',
    projectId: 'era-philippines',
    databaseURL:
        'https://era-philippines-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'era-philippines.appspot.com',
    iosBundleId: 'com.example.architecture',
  );
}
